"""The platform's checks on a generated frontend, and the screen registry.

pytest exercises the backend only, so for a while nothing ever ran the frontend.
A story went green, was reviewed, deployed and released with a page that threw
"api is not defined" on load and showed only the scaffold placeholder. These
checks run inside the build's repair loop, next to pytest, and their findings go
back to the Developer in the same output — so a broken screen is repaired before
anyone sees it, rather than discovered by the stakeholder after release.

Two layers:

* Static checks here in Python: JSX, dialogs standing in for an interface,
  placeholder comments, calls to API paths the backend does not serve, duplicate
  routes, and a story with no screen at all.
* Node in a throwaway container: every frontend file must parse, and every screen
  module must load without touching the DOM and export { title, render }.

The browser check after deploy (browser_check.py) covers what neither can: the
screens actually rendering against the live API.
"""
from __future__ import annotations

import ast
import asyncio
import re
from pathlib import Path

from .interface import (
    EXAMPLE_ROUTER,
    EXAMPLE_SCREEN,
    PACKAGE_DIR,
    REGISTRY,
    SCREENS_DIR,
    declared_routes,
    router_files,
)
from .repo import workspace_path
from .runner import ExecResult, mount_source, run_in_sandbox

NODE_IMAGE = "node:20-alpine"
SQL_IMAGE = "postgres:16-alpine"


def _screens_dir(run_id: str) -> Path:
    return workspace_path(run_id).joinpath(*SCREENS_DIR)


def screen_modules(run_id: str) -> list[Path]:
    d = _screens_dir(run_id)
    if not d.is_dir():
        return []
    return sorted(p for p in d.glob("*.js") if p.name != REGISTRY)


def story_screens(run_id: str) -> list[Path]:
    return [p for p in screen_modules(run_id) if p.name != EXAMPLE_SCREEN]


_STORY_TAG = re.compile(r"\bstor(?:y|ies)\s*:\s*([^\n]*)")


def stories_in(text: str) -> list[str]:
    """Story ids a screen declares it delivers: `story: "S1"` or `story: "S1, S3"`."""
    match = _STORY_TAG.search(text)
    return re.findall(r"\bS\d+\b", match.group(1)) if match else []


def regenerate_registry(run_id: str) -> list[str]:
    """Rewrite frontend/screens/index.js to list every story screen.

    ES modules cannot list a directory at runtime, so the registry is generated
    after every build step instead of edited by stories — no story can drop
    another's screen from it, and the worked example disappears once a real
    screen exists.
    """
    d = _screens_dir(run_id)
    if not d.is_dir():
        return []
    real = story_screens(run_id)
    chosen = real or [p for p in screen_modules(run_id) if p.name == EXAMPLE_SCREEN]

    def order(path: Path) -> tuple[int, str]:
        ids = stories_in(path.read_text(encoding="utf-8", errors="replace"))
        return (min((int(i[1:]) for i in ids), default=10**6), path.name)

    chosen.sort(key=order)
    lines = ["// Generated by Poiesis after every build step. Do not edit: it is rewritten."]
    lines += [f'import s{i} from "./{p.name}";' for i, p in enumerate(chosen)]
    lines += ["", "export default ["]
    lines += [
        f'  {{ id: "{p.stem}", example: {"true" if p.name == EXAMPLE_SCREEN else "false"}, module: s{i} }},'
        for i, p in enumerate(chosen)
    ]
    lines += ["];", ""]
    (d / REGISTRY).write_text("\n".join(lines), encoding="utf-8", newline="\n")
    return [p.stem for p in chosen]


# --- static checks ----------------------------------------------------------------

_COMMENTS = re.compile(r"//[^\n]*|/\*[\s\S]*?\*/")
_PLACEHOLDER = re.compile(r"\b(placeholder|todo|fixme|stub|not implemented|coming soon)\b", re.I)
_JSX = re.compile(r"return\s*\(\s*<|<>|</>|<[A-Z][A-Za-z0-9]*[\s/>]")
_API_CALL = re.compile(
    r"""\bapi\(\s*(?:(['"])(GET|POST|PUT|PATCH|DELETE)\1\s*,\s*)?(['"`])([^'"`]*)\3""", re.I
)
_BANNED: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"\b(alert|confirm|prompt)\s*\("),
     "calls {0}() — a dialog is not an interface. Show results and errors on the page, inside root"),
    (re.compile(r"\bfetch\s*\("),
     "calls fetch() directly — use the api() render() receives: it adds /api, sends JSON and reports failures"),
    (re.compile(r"""getElementById\(\s*['"]app['"]\s*\)|querySelector\(\s*['"]#app['"]\s*\)|document\.body"""),
     "reaches outside its own root — build the screen only inside the `root` element render() is given"),
    (re.compile(r"""window\.onload|DOMContentLoaded|addEventListener\(\s*['"]load['"]"""),
     "wires its own page startup — the shell calls render(); a screen must not"),
    (re.compile(r"""\bimport\s[^;\n]*from\s*['"](?!\.)"""),
     "imports a package — there is no bundler; use only relative imports of your own files"),
]


def _is_bare(path: str) -> bool:
    """A route at the root of /api: "/api/" itself, or "/api/{param}...".

    The second kind is the dangerous one. Mounted at /api, `@router.get("/{item_id}")`
    matches /api/anything, so it swallows every other story's GET and answers 422
    "item_id should be an integer" in their place.
    """
    rest = path[len("/api"):].strip("/") if path.startswith("/api") else path.strip("/")
    return rest == "" or rest.startswith("{")


def _route_pattern(route: str) -> re.Pattern[str]:
    # Trailing slashes are ignored on both sides: FastAPI redirects between them.
    escaped = re.escape(route.rstrip("/") or "/")
    escaped = re.sub(r"\\\{[^}]*\\\}", r"[^/]+", escaped)
    return re.compile(f"^{escaped}$")


def _normalise(path: str) -> str:
    path = path.split("?")[0].strip()
    path = re.sub(r"\$\{[^}]*\}", "x", path)
    if not path.startswith("/"):
        path = "/" + path
    if not re.match(r"^/api(/|$)", path):
        path = "/api" + path
    return path.rstrip("/") or "/api"


def static_issues(
    run_id: str, story_id: str | None, require_screen: bool, own_files: set[str] | None = None,
) -> list[str]:
    """Problems in the frontend and the route table.

    `own_files` are the files this story wrote. Router problems (a bare "/", a
    duplicate route) are reported only when this story's own file is involved:
    another story's leftover router is not something this story may edit, so
    failing it for one could never converge.
    """
    root = workspace_path(run_id)
    issues: list[str] = []
    routes = declared_routes(run_id)
    # A root catch-all ("/api/{id}") is not a real match for a screen's call: it
    # would pass /api/anything here and then answer 422 in the running app.
    patterns = [(r["method"], _route_pattern(r["path"])) for r in routes
                if not (_is_bare(r["path"]) and r["path"].rstrip("/") != "/api")]
    served = ", ".join(sorted({f"{r['method']} {r['path']}" for r in routes})) or "none"

    for path in story_screens(run_id):
        rel = path.relative_to(root).as_posix()
        text = path.read_text(encoding="utf-8", errors="replace")
        owners = stories_in(text)
        if story_id and owners and story_id not in owners:
            # Another story's screen: its own build checks it, and this story's
            # Developer is told not to edit it, so failing here could never converge.
            continue
        code = _COMMENTS.sub(" ", text)

        if "export default" not in code:
            issues.append(f"{rel}: has no `export default {{ title, story, render }}` — the shell cannot load it")
        if not stories_in(text):
            issues.append(f'{rel}: declares no story — add `story: "S1"` (the id of the story it delivers)')
        if _JSX.search(code):
            issues.append(f"{rel}: contains JSX — this is plain browser JavaScript; build elements with h()")
        for comment in _COMMENTS.findall(text):
            hit = _PLACEHOLDER.search(comment)
            if hit:
                issues.append(f"{rel}: a comment says '{hit.group(0)}' — a placeholder is not an implementation; "
                              "build the behaviour the acceptance criteria describe")
                break
        for pattern, message in _BANNED:
            hit = pattern.search(code)
            if hit:
                issues.append(f"{rel}: " + message.format(hit.group(1) if hit.groups() else ""))
        for call in _API_CALL.finditer(code):
            method = (call.group(2) or "").upper()
            called = _normalise(call.group(4))
            ok = any(p.match(called) and (not method or m == method) for m, p in patterns)
            if not ok:
                issues.append(f"{rel}: calls {method + ' ' if method else ''}{called}, which the API does not "
                              f"serve. Served routes: {served}")

    bare = sorted({r["file"] for r in routes
                   if r["file"].startswith("backend/app/routers/") and _is_bare(r["path"])})
    for rel in bare:
        if own_files is not None and rel not in own_files:
            continue
        issues.append(
            f"{rel}: declares routes at the root ('/' or '/{{id}}'), so they are served at /api/, "
            "where they collide with, or swallow, every other story's routes. Declare the "
            "resource on each route, e.g. "
            "@router.get(\"/llm-overviews\"), and call that same path from the screen."
        )

    seen: dict[tuple[str, str], str] = {}
    for r in routes:
        key = (r["method"], r["path"])
        if key in seen and (own_files is None or seen[key] in own_files or r["file"] in own_files):
            issues.append(f"{r['method']} {r['path']} is declared twice ({seen[key]} and {r['file']}) — "
                          "keep one: return the redundant file with empty content (\"\") and the "
                          "platform deletes it, or remove the route from it")
        seen[key] = r["file"]

    if require_screen and story_id:
        if not any(story_id in stories_in(p.read_text(encoding="utf-8", errors="replace"))
                   for p in story_screens(run_id)):
            issues.append(
                f"{story_id} has no screen. Add frontend/screens/<resource>.js whose default export includes "
                f'`story: "{story_id}"` (or add {story_id} to the `story` field of the existing screen it extends). '
                "A story a user cannot reach in the browser is not implemented."
            )

    for path in router_files(run_id):
        if path.name == EXAMPLE_ROUTER:
            continue  # the worked example is reference, not a story's own content
        rel = path.relative_to(root).as_posix()
        if own_files is not None and rel not in own_files:
            continue
        issues += _seeding_issues(run_id, path, rel)

    return list(dict.fromkeys(issues))  # one line per problem, however many calls repeat it


_TABLE_NAME = re.compile(r"__tablename__\s*=\s*[\"']([^\"']+)[\"']")
_INSERT_INTO = re.compile(r"INSERT\s+INTO\s+([A-Za-z_]\w*)", re.I)
_DB_QUERY = re.compile(r"\.query\(\s*([A-Za-z_]\w*)")
_TEST_SEED = re.compile(r"db_session\.add\(\s*([A-Za-z_]\w*)")


def _model_tables(run_id: str) -> dict[str, str]:
    """Class name -> table name, read from backend/app/models.py."""
    path = workspace_path(run_id).joinpath(*PACKAGE_DIR, "models.py")
    if not path.is_file():
        return {}
    try:
        tree = ast.parse(path.read_text(encoding="utf-8", errors="replace"))
    except SyntaxError:
        return {}
    out: dict[str, str] = {}
    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        for stmt in node.body:
            if (isinstance(stmt, ast.Assign) and len(stmt.targets) == 1
                    and isinstance(stmt.targets[0], ast.Name) and stmt.targets[0].id == "__tablename__"
                    and isinstance(stmt.value, ast.Constant) and isinstance(stmt.value.value, str)):
                out[node.name] = stmt.value.value
    return out


def _model_columns(run_id: str) -> dict[str, tuple[str, set[str]]]:
    """table name -> (class name, {column attribute names}), from models.py.

    Assumes the attribute name is the column name, true of every model this
    scaffold has produced (`name: Mapped[str] = mapped_column(...)`); a
    `relationship()` isn't a column and is excluded, since it names a class,
    not a table.
    """
    path = workspace_path(run_id).joinpath(*PACKAGE_DIR, "models.py")
    if not path.is_file():
        return {}
    try:
        tree = ast.parse(path.read_text(encoding="utf-8", errors="replace"))
    except SyntaxError:
        return {}
    out: dict[str, tuple[str, set[str]]] = {}
    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        table = None
        columns: set[str] = set()
        for stmt in node.body:
            if not (isinstance(stmt, (ast.Assign, ast.AnnAssign))):
                continue
            target = stmt.targets[0] if isinstance(stmt, ast.Assign) else stmt.target
            if not isinstance(target, ast.Name):
                continue
            if target.id == "__tablename__":
                if isinstance(stmt.value, ast.Constant) and isinstance(stmt.value.value, str):
                    table = stmt.value.value
                continue
            is_relationship = (isinstance(stmt.value, ast.Call) and isinstance(stmt.value.func, ast.Name)
                               and stmt.value.func.id == "relationship")
            if not is_relationship:
                columns.add(target.id)
        if table:
            out[table] = (node.name, columns)
    return out


_CREATE_TABLE = re.compile(
    r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?([A-Za-z_]\w*)\s*\((.*?)\)\s*;", re.I | re.S,
)
_SQL_CONSTRAINT_KEYWORDS = {"PRIMARY", "FOREIGN", "UNIQUE", "CONSTRAINT", "CHECK"}


def _split_top_level(body: str) -> list[str]:
    """Split a CREATE TABLE's column list on commas outside of `TYPE(...)` parens."""
    parts, current, depth = [], [], 0
    for ch in body:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append("".join(current))
            current = []
        else:
            current.append(ch)
    parts.append("".join(current))
    return parts


def _sql_columns(run_id: str) -> dict[str, set[str]]:
    """table name (lowercase) -> {column names}, from every CREATE TABLE in db/init.sql."""
    init = workspace_path(run_id) / "db" / "init.sql"
    if not init.is_file():
        return {}
    text = init.read_text(encoding="utf-8", errors="replace")
    out: dict[str, set[str]] = {}
    for m in _CREATE_TABLE.finditer(text):
        table, columns = m.group(1).lower(), set()
        for part in _split_top_level(m.group(2)):
            first = part.strip().strip('"').split()
            if not first or first[0].upper() in _SQL_CONSTRAINT_KEYWORDS:
                continue
            columns.add(first[0].strip('"').lower())
        out[table] = columns
    return out


def schema_drift_issues(run_id: str) -> list[str]:
    """A model column db/init.sql's matching table does not have.

    The two files are meant to move together — the Developer is told to add a
    model to models.py "and" its CREATE TABLE to init.sql — but nothing enforces
    it, and pytest cannot: its test database is built straight from the models
    via `Base.metadata.create_all`, which can never disagree with them. Real
    Postgres runs on db/init.sql alone, so a forgotten column passes every test
    and fails only in the deployed app, as `column ... does not exist`.
    """
    sql_tables = _sql_columns(run_id)
    issues = []
    for table, (cls, columns) in _model_columns(run_id).items():
        sql_cols = sql_tables.get(table.lower())
        if sql_cols is None:
            continue  # a missing table entirely is a louder, differently-shaped failure
        missing = sorted(columns - sql_cols)
        if missing:
            issues.append(
                f"backend/app/models.py: `{cls}` declares column(s) {', '.join(missing)} that "
                f"db/init.sql's `{table}` table does not have. Add {', '.join(missing)} to its "
                f"`CREATE TABLE {table}` statement — this cannot be caught by the tests, only by "
                "the real deployment, because the test database is built from the model directly."
            )
    return issues


def _seeded_tables(run_id: str) -> set[str]:
    """Tables with a starting row in db/init.sql, or seeded by a story's own test fixture."""
    seeded: set[str] = set()
    init = workspace_path(run_id) / "db" / "init.sql"
    if init.is_file():
        seeded |= {m.group(1).lower() for m in _INSERT_INTO.finditer(
            init.read_text(encoding="utf-8", errors="replace"))}
    return seeded


def _seeding_issues(run_id: str, path: Path, rel: str) -> list[str]:
    """A GET endpoint reading a table nothing ever inserts a row into.

    A story that must show content on a fresh deployment — before any user has
    created anything — fails at exactly the moment that matters if that content
    lives in a database table with no seed data: unit tests miss this because a
    Tester routinely seeds the row itself with the `db_session` fixture inside
    the test, which proves nothing about the real, empty, deployed database.
    A GET endpoint that only forwards a bare `.query(Model)...` call, backed by
    a table with no `INSERT INTO` anywhere in db/init.sql, is flagged here
    directly against the failing test, which reads far more as an instruction
    than a paragraph in the system prompt does.
    """
    text = path.read_text(encoding="utf-8", errors="replace")
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return []
    tables = _model_tables(run_id)
    seeded = _seeded_tables(run_id)
    issues: list[str] = []
    for node in tree.body:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        is_get = any(isinstance(d, ast.Call) and isinstance(d.func, ast.Attribute) and d.func.attr == "get"
                     for d in node.decorator_list)
        if not is_get:
            continue
        src = ast.get_source_segment(text, node) or ""
        if "return [" in src or "return {" in src or "return (" in src:
            continue  # returns a literal itself; not the empty-table pattern
        match = _DB_QUERY.search(src)
        if not match:
            continue
        model = match.group(1)
        table = tables.get(model)
        if table and table.lower() not in seeded:
            issues.append(
                f"{rel}: its GET endpoint returns `{model}` rows from the database, but nothing "
                f"seeds the `{table}` table — no `INSERT INTO {table}` in db/init.sql, and no other "
                "code populates it. On a fresh deployment, before any user has created anything, "
                "this endpoint returns an empty list and the screen has nothing to show, however "
                "the tests seeded their own copy of the database and passed. If the story's content "
                "is fixed rather than user-entered, return it as a literal from the endpoint instead "
                f"of querying the database; if it is real starting data, add `INSERT INTO {table}` "
                "statements to db/init.sql so a fresh deployment is never empty."
            )
    return issues


# --- the generated backend's own Python ----------------------------------------------

def _story_python(run_id: str, own_files: set[str] | None) -> list[tuple[str, str]]:
    """(path, source) for the backend Python this story wrote — never the scaffold's."""
    root = workspace_path(run_id)
    out: list[tuple[str, str]] = []
    for path in router_files(run_id):
        if path.name == EXAMPLE_ROUTER:
            continue
        rel = path.relative_to(root).as_posix()
        if own_files is not None and rel not in own_files:
            continue
        out.append((rel, path.read_text(encoding="utf-8", errors="replace")))
    return out


def backend_issues(run_id: str, own_files: set[str] | None = None) -> list[str]:
    """The handful of Python mistakes the Developer makes over and over.

    Taken from run history rather than imagined. Across fourteen runs the same
    few errors accounted for about half of every story that went red, and each
    one cost a full repair round to rediscover through a traceback:

    * `db = db.get_session()` — a helper shadowing the module it is calling, so
      every request raises UnboundLocalError. The tests pass anyway whenever
      they exercise a different router, and it surfaces only in the browser.
    * `from backend.app import ...` — a path that exists in the repository tree
      but not on the import path, so pytest cannot even collect the module and
      the whole suite reports as one error.
    * a SQLAlchemy model handed to `response_model=`, which fails at import and
      takes the entire application down with it, smoke tests included.

    Each is one AST walk to find here, before pytest runs at all.
    """
    models = set(_model_tables(run_id))
    issues: list[str] = []
    for rel, src in _story_python(run_id, own_files):
        if re.search(r"^\s*(?:from|import)\s+backend[.\s]", src, re.M):
            issues.append(
                f"{rel}: imports `backend...`, a path that does not exist at runtime or under "
                "test — pytest cannot even collect a module that does this, so the whole suite "
                "fails as one error. The package root is `app`: import siblings with two dots "
                "(`from ..db import get_session`, `from ..models import Thing`)."
            )
        try:
            tree = ast.parse(src)
        except SyntaxError as exc:
            issues.append(f"{rel}: does not parse as Python — {exc.msg} at line {exc.lineno}.")
            continue

        for node in ast.walk(tree):
            # `db = db.get_session()` — the name being assigned is the very module
            # the call is reaching through, so the local shadows it and the lookup
            # happens before assignment: UnboundLocalError on every request.
            if (isinstance(node, ast.Assign) and len(node.targets) == 1
                    and isinstance(node.targets[0], ast.Name)
                    and isinstance(node.value, ast.Call)
                    and isinstance(node.value.func, ast.Attribute)
                    and isinstance(node.value.func.value, ast.Name)
                    and node.value.func.value.id == node.targets[0].id):
                name = node.targets[0].id
                issues.append(
                    f"{rel}: `{name} = {name}.{node.value.func.attr}()` shadows the module it is "
                    f"calling — Python treats `{name}` as local for the whole function, so the "
                    "call raises UnboundLocalError on every request. Take the session as a "
                    "parameter instead: `def endpoint(db: Session = Depends(get_session))`, "
                    "exactly as routers/examples.py does."
                )

            if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute):
                for kw in node.keywords:
                    if kw.arg != "response_model":
                        continue
                    target = kw.value
                    if (isinstance(target, ast.Subscript) and isinstance(target.slice, ast.Name)):
                        target = target.slice
                    if isinstance(target, ast.Name) and target.id in models:
                        issues.append(
                            f"{rel}: `response_model={target.id}` names a SQLAlchemy model. "
                            "FastAPI raises `Invalid args for response field` at import time, "
                            "which takes the whole application down — every test fails, "
                            "including the scaffold's own. response_model must be a Pydantic "
                            f"schema from schemas.py (e.g. `{target.id}Out`); return the ORM "
                            "object and let it serialise."
                        )

        if re.search(r"\bstrptime\s*\(", src):
            issues.append(
                f"{rel}: calls strptime(). A field typed `datetime.date` in the schema is "
                "already parsed by FastAPI before your function runs, so parsing it again "
                "raises TypeError on a value that is a date, not a string. Type the field and "
                "use it directly."
            )
    return list(dict.fromkeys(issues))


# --- the Tester's own output ----------------------------------------------------------

_CLIENT_CALL = re.compile(
    r"""\bclient\.(get|post|put|patch|delete)\(\s*f?(['"])([^'"]+)\2""", re.I)
_STATUS_ASSERT = re.compile(r"status_code\s*==\s*(\d{3})")
_NONEMPTY = re.compile(r"len\([^)]*\)\s*>\s*0|\)\s*\[0\]|assert\s+(?:body|rows|data|result)\s*$", re.M)
_MARKUP = re.compile(r"""assert\s+['"][^'"]*<[a-zA-Z/][^'"]*['"]""")
_LABELISH = re.compile(r"""assert\s+['"]([A-Z][A-Za-z ]{2,30})['"]\s+in\s+\w+\[""")
_SEEDS = re.compile(r"client\.post\(|db_session\.add\(")


def test_issues(run_id: str, test_paths: list[str]) -> list[str]:
    """Tests that cannot pass however correct the implementation is.

    The Tester writes its suite once, before a line of it has ever run, and the
    Developer is forbidden to edit tests — rightly, since that is what stops a
    model writing tests that pass. The cost of that rule is that an impossible
    test is unfixable by anyone until the Tester is asked again, which used to
    happen only after three Developer repairs had already been spent on code
    that was never wrong. These are the shapes that actually showed up:
    `assert 405 == 422` (a POST to a path serving only GET), `assert 0 > 0`
    (rows expected from a database nothing seeded), and a button's label
    asserted inside a JSON body. Catching them here costs one Tester revision
    instead of a whole story.
    """
    root = workspace_path(run_id)
    routes = declared_routes(run_id)
    served = ", ".join(sorted({f"{r['method']} {r['path']}" for r in routes})) or "none"
    by_path: dict[str, set[str]] = {}
    status_for: dict[tuple[str, str], int] = {}
    for r in routes:
        key = r["path"].rstrip("/") or "/"
        by_path.setdefault(key, set()).add(r["method"])
        status_for[(r["method"], key)] = r["status"]

    issues: list[str] = []
    for rel in test_paths:
        target = root / rel
        if not target.is_file():
            continue
        src = target.read_text(encoding="utf-8", errors="replace")
        for block in re.split(r"^(?=\s*(?:async\s+)?def\s+test_)", src, flags=re.M):
            name_match = re.search(r"def\s+(test_\w+)", block)
            if not name_match:
                continue
            name = name_match.group(1)
            for call in _CLIENT_CALL.finditer(block):
                method, path = call.group(1).upper(), _normalise(call.group(3))
                path = path.rstrip("/") or "/"
                matches = [p for p in by_path if _route_pattern(p).match(path)]
                if not matches:
                    issues.append(
                        f"{rel}::{name} requests {method} {path}, which the API does not serve. "
                        f"Served routes: {served}. Test what exists, or leave the criterion in "
                        "criteria_not_covered."
                    )
                    continue
                allowed = set().union(*(by_path[p] for p in matches))
                if method not in allowed:
                    issues.append(
                        f"{rel}::{name} sends {method} {path}, but that path serves only "
                        f"{', '.join(sorted(allowed))} — FastAPI answers 405 and no "
                        "implementation can change that. Either the story needs that endpoint "
                        "(say so and test it once it exists) or the assertion does not belong."
                    )
                    continue
                expected = {int(m) for m in _STATUS_ASSERT.findall(block)}
                declared = {status_for[(method, p)] for p in matches if (method, p) in status_for}
                if expected and declared and not (expected & declared) and not (expected & {422, 404, 400, 405}):
                    issues.append(
                        f"{rel}::{name} expects status {sorted(expected)} from {method} {path}, "
                        f"which the route declares as {sorted(declared)}. Assert the status the "
                        "contract states."
                    )
            if _NONEMPTY.search(block) and not _SEEDS.search(block):
                issues.append(
                    f"{rel}::{name} asserts a non-empty result but never creates the data it "
                    "expects — the test database starts empty, so this fails whatever the "
                    "implementation does. Create the row first (client.post, or db_session.add "
                    "then commit), or assert the shape of an empty result instead."
                )
            if _MARKUP.search(block):
                issues.append(
                    f"{rel}::{name} asserts HTML in an API response. The API returns data; the "
                    "markup lives in the screen, which the platform checks in a real browser. "
                    "Assert the data behind it."
                )
            hit = _LABELISH.search(block)
            if hit:
                issues.append(
                    f"{rel}::{name} asserts the label \"{hit.group(1)}\" inside a response field. "
                    "A button or link label belongs to the screen, not the payload."
                )
            for literal in re.findall(r"""==\s*['"]([^'"]{140,})['"]""", block):
                issues.append(
                    f"{rel}::{name} compares against {len(literal)} characters of text copied "
                    "verbatim. Content changes wording without changing meaning; assert that it "
                    "is present and names the key terms instead."
                )
    return list(dict.fromkeys(issues))


# --- routers declared at "/" --------------------------------------------------------

_TEST_CALL = re.compile(r"""\bclient\.(get|post|put|patch|delete)\(\s*f?(['"])([^'"]+)\2""", re.I)
_BARE_DECORATOR = re.compile(r"""(@router\.(?:get|post|put|patch|delete)\(\s*)(['"])/(\{[^'"]*|)\2""")


def _called_paths(run_id: str) -> list[str]:
    """Every /api path the story screens and the tests request, normalised."""
    root = workspace_path(run_id)
    paths: list[str] = []
    for p in story_screens(run_id):
        code = _COMMENTS.sub(" ", p.read_text(encoding="utf-8", errors="replace"))
        paths += [_normalise(m.group(4)) for m in _API_CALL.finditer(code)]
    tests = root / "tests"
    if tests.is_dir():
        for p in tests.glob("test_*.py"):
            text = p.read_text(encoding="utf-8", errors="replace")
            # Tests request full URLs. Only /api ones are story endpoints: the
            # smoke tests' /health and /openapi.json are not, and counting them
            # made every caller set look ambiguous, so no router was ever moved.
            paths += [_normalise(m.group(3)) for m in _TEST_CALL.finditer(text)
                      if m.group(3).startswith("/api/")]
    return paths


def mount_bare_routers(run_id: str) -> list[str]:
    """Give a story router declared at "/" the resource path its callers already use.

    A local model wrote `@router.get("/")` while its own screen and tests
    requested /api/llm-overviews, and kept the bare path through three repairs
    with the served routes listed back to it each time. Worse, once repairs ran
    out the Tester was told that tests contradicting the verified routes are
    wrong — so it would have "fixed" correct tests to match the broken router.

    When exactly one story router is declared at "/" and its callers agree on
    exactly one path that nothing serves, its decorators are rewritten to that
    path. Tests and the browser check still judge the result; this only removes
    a mismatch every caller already agrees on, and never guesses between two.
    """
    routes = declared_routes(run_id)
    bare = sorted({r["file"] for r in routes
                   if r["file"].startswith("backend/app/routers/") and _is_bare(r["path"])})
    if len(bare) != 1:
        return []
    # The bare router's own routes do not count as serving anything: its
    # "/{item_id}" would otherwise match every path its callers use.
    patterns = [_route_pattern(r["path"]) for r in routes if r["file"] != bare[0]]
    bases = {
        path.split("/")[2]
        for path in _called_paths(run_id)
        if path.count("/") >= 2 and not any(p.match(path) for p in patterns)
    }
    if len(bases) != 1:
        return []
    base = bases.pop()
    if not re.fullmatch(r"[A-Za-z0-9_-]+", base):
        return []
    target = workspace_path(run_id) / bare[0]
    text = target.read_text(encoding="utf-8", errors="replace")
    if re.search(r"APIRouter\([^)]*prefix\s*=", text):
        return []

    def _rewrite(m: re.Match[str]) -> str:
        rest = f"/{m.group(3)}" if m.group(3) else ""
        return f"{m.group(1)}{m.group(2)}/{base}{rest}{m.group(2)}"

    fixed = _BARE_DECORATOR.sub(_rewrite, text)
    if fixed == text:
        return []
    target.write_text(fixed, encoding="utf-8")
    return [f"{bare[0]} declared its routes at '/'; the platform moved them to /api/{base}, "
            "the path its screen and tests call"]


# --- node checks in a sandbox ---------------------------------------------------------

NODE_SCRIPT = r"""
import { readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import { spawnSync } from "node:child_process";
import { pathToFileURL } from "node:url";

const root = process.argv[2];
const problems = [];
const walk = (dir) => readdirSync(dir).flatMap((name) => {
  const p = join(dir, name);
  return statSync(p).isDirectory() ? walk(p) : [p];
});

// Problems are separated by blank lines and must not contain any: the platform
// splits on them to keep each story's report to its own files.
const unparsable = new Set();
for (const file of walk(root).filter((f) => f.endsWith(".js"))) {
  const r = spawnSync(process.execPath, ["--check", file], { encoding: "utf8" });
  if (r.status !== 0) {
    const detail = (r.stderr || "").split("\n").filter((l) => l.trim() && !/^\s+at /.test(l))
      .slice(0, 5).join("\n");
    problems.push(`frontend/${relative(root, file)}: JavaScript syntax error\n${detail}`);
    unparsable.add(file);
  }
}

const dir = join(root, "screens");
let names = [];
try { names = readdirSync(dir).filter((n) => n.endsWith(".js") && n !== "index.js"); } catch {}
for (const name of names) {
  const rel = `frontend/screens/${name}`;
  if (unparsable.has(join(dir, name))) continue; // already reported as a syntax error
  try {
    const screen = (await import(pathToFileURL(join(dir, name)).href)).default;
    if (!screen || typeof screen !== "object") {
      problems.push(`${rel}: must \`export default { title, story, render }\` — found no default export object`);
      continue;
    }
    if (typeof screen.title !== "string" || !screen.title.trim()) {
      problems.push(`${rel}: the default export needs a non-empty \`title\` string (the navigation label)`);
    }
    if (typeof screen.render !== "function") {
      problems.push(`${rel}: the default export needs a \`render(root, { api, h, navigate, params })\` function`);
    }
  } catch (err) {
    const message = String((err && err.message) || err).split("\n")[0];
    problems.push(`${rel}: failed to load — ${message}. Nothing at the top level of a screen may touch `
      + "document, window or fetch; do that inside render().");
  }
}

if (problems.length) {
  console.log(problems.join("\n\n"));
  process.exit(1);
}
console.log(`frontend ok: every file parses; ${names.length} screen(s) load and export { title, render }`);
"""

# A copy with a package.json so Node treats the screens as ES modules. The
# workspace itself stays untouched, and the container has no network.
NODE_COMMAND = (
    "mkdir -p /tmp/fe && cp -r /work/frontend/. /tmp/fe/ && "
    "printf '{\"type\":\"module\"}' > /tmp/fe/package.json && "
    "node /work/.poiesis/check_frontend.mjs /tmp/fe"
)

def _foreign_screens(run_id: str, story_id: str | None) -> set[str]:
    """Screens that belong to other stories, as workspace-relative paths."""
    if not story_id:
        return set()
    root = workspace_path(run_id)
    out: set[str] = set()
    for p in story_screens(run_id):
        owners = stories_in(p.read_text(encoding="utf-8", errors="replace"))
        if owners and story_id not in owners:
            out.add(p.relative_to(root).as_posix())
    return out


HEADER = "\n\n=== PLATFORM CHECKS: the frontend (implementation problems for the Developer, not test problems) ===\n"


async def _proc(*cmd: str, timeout: int = 60) -> tuple[int, str]:
    proc = await asyncio.create_subprocess_exec(
        *cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.STDOUT,
    )
    try:
        out, _ = await asyncio.wait_for(proc.communicate(), timeout=timeout)
    except asyncio.TimeoutError:
        proc.kill()
        return -1, f"timed out after {timeout}s"
    return (proc.returncode if proc.returncode is not None else -1), out.decode(errors="replace")


async def validate_init_sql(run_id: str) -> ExecResult:
    """Actually run db/init.sql against a throwaway Postgres. Nothing else does.

    pytest builds its tables from the SQLAlchemy models via `Base.metadata.
    create_all` — never from init.sql — so a syntactically broken init.sql
    (most often a reply truncated mid-statement) passes every test cleanly and
    is discovered only when the real database container crash-loops at deploy
    time, taking the whole application down. Running it here, in the repair
    loop, catches exactly what deploy would hit, attributed to the story that
    is being built right now instead of an unattributed "the app didn't start"
    finding that forces the entire sprint to be rebuilt to fix one file.
    """
    root = workspace_path(run_id)
    init = root / "db" / "init.sql"
    if not init.is_file():
        return ExecResult(0, "", "", False)

    name = f"poiesis-sqlcheck-{run_id}"
    await _proc("docker", "rm", "-f", name, timeout=20)
    mount = f"{mount_source(run_id)}/db/init.sql"
    started = False
    try:
        code, out = await _proc(
            "docker", "run", "-d", "--name", name,
            "-e", "POSTGRES_PASSWORD=poiesis", "-e", "POSTGRES_DB=poiesis",
            "-v", f"{mount}:/tmp/init.sql:ro",
            SQL_IMAGE, timeout=30,
        )
        if code != 0:
            return ExecResult(0, "", "", False)  # docker itself unavailable; not this check's job
        started = True
        for _ in range(30):
            code, _ = await _proc("docker", "exec", name, "pg_isready", "-U", "postgres", timeout=10)
            if code == 0:
                break
            await asyncio.sleep(0.5)
        else:
            return ExecResult(0, "", "", False)  # never came up; a real deploy will surface why

        code, out = await _proc(
            "docker", "exec", name, "psql", "-U", "postgres", "-d", "poiesis",
            "-v", "ON_ERROR_STOP=1", "-f", "/tmp/init.sql", timeout=30,
        )
    finally:
        if started:
            await _proc("docker", "rm", "-f", name, timeout=20)

    if code == 0:
        return ExecResult(0, "", "", False)
    lines = [l for l in out.splitlines() if l.strip()]
    return ExecResult(1, "\n".join(lines[-15:]), "", False)


async def platform_checks(
    run_id: str, story_id: str | None, require_screen: bool, own_files: set[str] | None = None,
) -> ExecResult:
    """Static, Node and database checks, as one ExecResult the repair loop can read."""
    root = workspace_path(run_id)
    issues: list[str] = []

    sql = await validate_init_sql(run_id)
    if not sql.ok:
        issues.append(
            "db/init.sql failed when actually executed against Postgres — pytest never "
            "catches this, because it builds its test tables from the Python models instead "
            f"of running init.sql:\n{sql.stdout}"
        )
    else:
        # Only meaningful once init.sql is known to at least run: a column missing
        # from a table that itself failed to create would just be noise on top.
        issues += schema_drift_issues(run_id)

    issues += backend_issues(run_id, own_files)

    if not (root / "frontend").is_dir():
        body = "\n\n".join(f"- {i}" for i in issues)
        return ExecResult(0 if not issues else 1, (HEADER + body) if issues else "", "", False)

    issues += static_issues(run_id, story_id, require_screen, own_files)
    tools = root / ".poiesis"
    tools.mkdir(exist_ok=True)
    (tools / "check_frontend.mjs").write_text(NODE_SCRIPT, encoding="utf-8", newline="\n")
    node = await run_in_sandbox(
        run_id, NODE_COMMAND, image=NODE_IMAGE, shell="sh", network=False, timeout=180
    )
    node_out = (node.stdout + "\n" + node.stderr).strip()
    if not node.ok:
        blocks = [b.strip() for b in node_out.split("\n\n") if b.strip()]
        foreign = _foreign_screens(run_id, story_id)
        mine = [b for b in blocks if b.split(":", 1)[0].strip() not in foreign]
        if mine:
            issues += mine
        elif not blocks:
            issues.append("The frontend check could not run.")
        else:
            node_out = "frontend ok for this story (other stories' screens have their own checks)"

    body = "\n\n".join(f"- {i}" for i in issues) if issues else node_out
    return ExecResult(0 if not issues else 1, HEADER + body, "", False)


# --- keeping shared files whole ---------------------------------------------------------

SHARED_PY = ("backend/app/models.py", "backend/app/schemas.py")
SHARED_SQL = "db/init.sql"
_TABLE = re.compile(r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?([A-Za-z_]\w*)\s*\([\s\S]*?\)\s*;", re.I)


def _elsewhere(root: Path, skip: str, proposed: dict[str, str]) -> str:
    """Everything in the backend and tests except one file, including proposed edits."""
    texts: list[str] = []
    for base in ("backend", "tests"):
        for p in (root / base).rglob("*.py"):
            rel = p.relative_to(root).as_posix()
            if rel != skip and rel not in proposed:
                texts.append(p.read_text(encoding="utf-8", errors="replace"))
    texts += [body for rel, body in proposed.items() if rel != skip]
    return "\n".join(texts)


def preserve_shared(run_id: str, files: dict[str, str]) -> tuple[dict[str, str], list[str]]:
    """Put back what a rewrite of a shared file dropped, when something still uses it.

    Stories return schemas.py, models.py and init.sql complete. A model that is
    shown a truncated copy, or simply forgets, drops an earlier story's class and
    breaks that story at import time. Dropped definitions still referenced
    elsewhere are re-appended (with the imports they came with); dropped tables
    are always restored, because a model depends on them.
    """
    root = workspace_path(run_id)
    out = dict(files)
    restored: list[str] = []

    for rel in SHARED_PY:
        new = out.get(rel)
        current = root / rel
        if new is None or not current.is_file():
            continue
        old = current.read_text(encoding="utf-8", errors="replace")
        try:
            old_tree, new_tree = ast.parse(old), ast.parse(new)
        except SyntaxError:
            continue
        defs = (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)
        kept = {n.name for n in new_tree.body if isinstance(n, defs)}
        others = _elsewhere(root, rel, out)
        lost = [n for n in old_tree.body if isinstance(n, defs) and n.name not in kept
                and re.search(rf"\b{re.escape(n.name)}\b", others)]
        if not lost:
            continue
        imports = (ast.Import, ast.ImportFrom)
        have = {ast.get_source_segment(new, n) for n in new_tree.body if isinstance(n, imports)}
        missing = [s for n in old_tree.body if isinstance(n, imports)
                   and (s := ast.get_source_segment(old, n)) and s not in have and "__future__" not in s]
        lines = new.rstrip("\n").splitlines()
        last = max((n.end_lineno or 0 for n in new_tree.body if isinstance(n, imports)), default=0)
        segments = [ast.get_source_segment(old, n) or "" for n in lost]
        merged = "\n".join(lines[:last] + missing + lines[last:]) + "\n\n\n" + "\n\n\n".join(segments) + "\n"
        try:
            ast.parse(merged)
        except SyntaxError:
            continue
        out[rel] = merged
        restored += [f"{rel}: {n.name}" for n in lost]

    new_sql = out.get(SHARED_SQL)
    current_sql = root / SHARED_SQL
    if new_sql is not None and current_sql.is_file():
        old_sql = current_sql.read_text(encoding="utf-8", errors="replace")
        kept_tables = {m.group(1).lower() for m in _TABLE.finditer(new_sql)}
        lost_tables = [m for m in _TABLE.finditer(old_sql) if m.group(1).lower() not in kept_tables]
        if lost_tables:
            out[SHARED_SQL] = (new_sql.rstrip() + "\n\n"
                               + "\n\n".join(m.group(0) for m in lost_tables) + "\n")
            restored += [f"{SHARED_SQL}: {m.group(1)}" for m in lost_tables]
    return out, restored
