/* Every component of the kit on one page, from fixed data, so each can be looked at. */
import fin from "../finance.js";

export default {
  title: "Component gallery", icon: "grid", story: "S9",
  async render(root, { ui, h }) {
    const chosen = h("pre", { id: "chosen", class: "json" }, "{}");
    const say = (v) => { chosen.textContent = JSON.stringify(v); };
    const months = ["Apr 2026", "May 2026", "Jun 2026", "Jul 2026", "Aug 2026", "Sep 2026", "Oct 2026"];
    const points = months.map((label, i) => ({ label, value: [410000, 455000, 438000, 502000, 471000, 388000, 0][i], budget: 460000 + i * 4000,
      prior: [380000, 420000, 445000, 430000, 465000, 450000, 470000][i], partial: i === 5, future: i === 6 }));
    root.replaceChildren(
      ui.section("Text", { icon: "file" }, h("div", { class: "row", id: "text" },
        ...[fin.money(1234567.5), fin.money(1234567.5, { compact: true }), fin.money(-420, { accounting: true }), fin.money(48250, { compact: true, currency: "EUR" }),
          fin.money(null), fin.money("abc"), fin.money(NaN), fin.percent(12.345), fin.percent(-2.1, { signed: true }), fin.percent(undefined), fin.days(1), fin.days(10.6),
          fin.number(null), fin.format(3.2, "pct", { points: true }), fin.date("2026-09-25"), fin.date(null), fin.words("price_variance")]
          .map((t) => h("code", {}, t)))),
      ui.section("Deltas and variances", { icon: "activity" }, h("div", { class: "row" },
        fin.delta(4.2, { good: "down" }), fin.delta(4.2, { good: "up" }), fin.delta(-3, { good: "down", label: "vs last year" }), fin.delta(0, { good: "up" }),
        fin.delta(null), fin.delta(2.5, {}), fin.delta(1.4, { good: "up", points: true }),
        fin.varianceBadge(104000, 100000), fin.varianceBadge(94000, 100000), fin.varianceBadge(100000, 100000), fin.varianceBadge(null, 5),
        fin.status("price_variance"), fin.status("over"), fin.status("on_track"), fin.status(null), fin.status("notice_due"))),
      ui.section("Headline figures", { icon: "chart" }, fin.kpis([
        { key: "spend", label: "Spend", unit: "money", value: 2818497.82, change_pct: 6.4, favourable: null, good: "", spark: [4, 5, 4, 6, 5, 7], icon: "dollar", drill: { entity: "invoice" } },
        { key: "po_coverage", label: "Spend on a purchase order", unit: "pct", value: 89, change_pct: 2.1, favourable: true, good: "up", spark: [80, 84, 86, 85, 88, 89], target: 95 },
        { key: "overdue", label: "Overdue payables", unit: "money", value: 110339.86, good: "down", position: true },
        { key: "cycle", label: "Invoice approval time", unit: "days", value: 10.6, change_pct: 12, favourable: false, good: "down", spark: [8, 9, 9, 10, 11, 10.6], target: 8 },
        { key: "none", label: "Nothing known", unit: "money", value: null, change_pct: null, spark: [] },
      ], { compare: "vs last year", onClick: say })),
      h("div", { class: "grid-2" },
        ui.section("Trend", { icon: "activity" }, fin.trend(points, { onClick: say })),
        ui.section("Running total", { icon: "activity" }, fin.trend(points.map((p, i, all) => ({ ...p,
          cumulative: all.slice(0, i + 1).reduce((a, x) => a + x.value, 0), cumulative_budget: all.slice(0, i + 1).reduce((a, x) => a + x.budget, 0) })),
        { cumulative: true, series: ["value", "budget"] }))),
      h("div", { class: "grid-2" },
        ui.section("Budget bars", { icon: "dollar" }, fin.budgetBars([
          { label: "Software Engineering", budget: 390000, actual: 456000, status: "over", year_budget: 800000, year_actual: 456000, committed: 210000, available: 134000, position: "ok" },
          { label: "Logistics & Distribution", budget: 520000, actual: 531000, status: "watch", year_budget: 1040000, year_actual: 531000, committed: 560000, available: -51000, position: "exceeded" },
          { label: "Marketing", budget: 210000, actual: 176000, status: "on_track", year_budget: 430000, year_actual: 176000, committed: 40000, available: 214000, position: "ok" },
          { label: "Unbudgeted team", budget: 0, actual: 12000, status: "unbudgeted", year_budget: 0, year_actual: 12000, committed: 0, available: -12000, position: "exceeded" },
        ], { onClick: say })),
        ui.section("Budget bars, full year", { icon: "dollar" }, fin.budgetBars([
          { label: "Software Engineering", budget: 390000, actual: 456000, status: "over", year_budget: 800000, year_actual: 456000, committed: 210000, available: 134000, position: "ok" },
          { label: "Logistics & Distribution", budget: 520000, actual: 531000, status: "watch", year_budget: 1040000, year_actual: 531000, committed: 560000, available: -51000, position: "exceeded" },
        ], { view: "year", elapsed: 48.8 }))),
      h("div", { class: "grid-2" },
        ui.section("Waterfall", { icon: "chart" }, fin.waterfall({ start: { label: "Budget", value: 3120000 },
          steps: [{ key: 1, label: "Software Engineering", value: 66000, favourable: false }, { key: 2, label: "Marketing", value: -34000, favourable: true },
            { key: 3, label: "Logistics", value: 11000, favourable: false }, { key: null, label: "Other (9)", value: -120000, favourable: true }],
          end: { label: "Actual", value: 3043000 } }, { onClick: say })),
        ui.section("Waterfall from zero", { icon: "chart" }, fin.waterfall({ start: { label: "Identified", value: 100000 },
          steps: [{ key: 1, label: "Cancelled", value: -30000, favourable: false }, { key: 2, label: "In progress", value: -45000, favourable: false }],
          end: { label: "Realised", value: 25000 } }))),
      h("div", { class: "grid-2" },
        ui.section("Pareto", { icon: "chart" }, fin.pareto(Array.from({ length: 22 }, (_, i) => ({ key: i + 1, label: `Supplier number ${i + 1} Ltd`, value: Math.round(400000 / (i + 1)), count: 30 - i })), { onClick: say })),
        ui.section("Treemap", { icon: "grid" }, fin.treemap(Array.from({ length: 18 }, (_, i) => ({ key: i + 1, label: ["Software & SaaS", "Freight", "Contractors", "Cloud hosting", "Legal", "Travel"][i % 6] + (i > 5 ? ` ${i}` : ""),
          value: Math.round(900000 / (i + 1.4)) })), { onClick: say }))),
      h("div", { class: "grid-2" },
        ui.section("Donut", { icon: "pie" }, fin.donut([{ key: "IT", label: "IT", value: 900000 }, { key: "F", label: "Facilities and a very long family name", value: 410000.5 },
          { key: "P", label: "Professional services", value: 380000 }, { key: "Z", label: "Nothing", value: 0 }], { sub: "spend", onClick: say })),
        ui.section("Ageing", { icon: "clock" }, fin.aging([{ label: "Not due", value: 640000, count: 61, share_pct: 73.3, overdue: false }, { label: "1-30", value: 120000, count: 14, share_pct: 13.7, overdue: true },
          { label: "31-60", value: 62000, count: 6, share_pct: 7.1, overdue: true }, { label: "61-90", value: 0, count: 0, share_pct: 0, overdue: true },
          { label: "90+", value: 51567.53, count: 1, share_pct: 5.9, overdue: true }], { onClick: say }))),
      h("div", { class: "grid-2" },
        ui.section("Funnel", { icon: "filter" }, fin.funnel([{ label: "Requested", count: 140, value: 1900000, of_previous_pct: null }, { label: "Approved", count: 118, value: 1600000, of_previous_pct: 84.3 },
          { label: "Ordered", count: 104, value: 1500000, of_previous_pct: 88.1 }, { label: "Received", count: 80, value: 1200000, of_previous_pct: 76.9 },
          { label: "Invoiced", count: 71, value: 1000000, of_previous_pct: 88.8 }, { label: "Paid", count: 52, value: 700000, of_previous_pct: 73.2 }])),
        ui.section("Cycle times", { icon: "history" }, fin.cycleTimes([{ label: "Requisition: submitted to approved", average_days: 1.8, median_days: 1.5, p90_days: 4, count: 118, prior_average_days: 2.4 },
          { label: "Invoice: received to approved", average_days: 10.6, median_days: 9, p90_days: 21, count: 300, prior_average_days: 9.1 },
          { label: "Invoice: approved to paid", average_days: 16.9, median_days: 15, p90_days: 30, count: 280, prior_average_days: null }]))),
      ui.section("Cross-tab", { icon: "grid" }, fin.pivot({ row_by: "cost_center", column_by: "month", columns: months.slice(0, 6).map((m, i) => ({ key: `2026-0${i + 4}-01`, label: m })),
        rows: [{ key: 1, label: "Software Engineering", total: 456000, cells: [70000, 80000, 76000, 90000, 84000, 56000] }, { key: 2, label: "Marketing", total: 176000, cells: [30000, 0, 36000, 40000, 44000, 26000] }],
        totals: [100000, 80000, 112000, 130000, 128000, 82000], total: 632000 }, { exportable: "gallery", onClick: (r, c, v) => say({ row: r.label, column: c.label, v }) })),
      h("div", { class: "grid-2" },
        ui.section("Three-way match", { icon: "check" }, h("div", { class: "stack" },
          fin.matchStatus({ status: "matched", ordered: 10000, received: 10000, invoiced: 10000 }),
          fin.matchStatus({ status: "price_variance", ordered: 10000, received: 10000, invoiced: 10420, discrepancies: ["The invoice is £420.00 above what was received; the tolerance is 2% and £50."] }),
          fin.matchStatus({ status: "no_receipt", ordered: 5000, received: null, invoiced: 5000 }),
          fin.matchStatus({ status: "no_po", ordered: null, received: null, invoiced: 880.5 }))),
        ui.section("Approvals and lifecycle", { icon: "check-circle" }, h("div", { class: "stack" },
          fin.approvalChain(18400, [{ up_to: 5000, role: "budget_holder" }, { up_to: 25000, role: "head_of_department" }, { up_to: 100000, role: "finance_director" }, { up_to: null, role: "cfo" }],
            { roles: { budget_holder: "Budget holder", head_of_department: "Head of department", finance_director: "Finance director", cfo: "Chief financial officer" } }),
          fin.approvalChain(260000, [[5000, "budget_holder"], [25000, "head_of_department"], [100000, "finance_director"], [null, "cfo"]],
            { decided: [{ role: "cfo", by: "Sofia Lindgren", status: "approved" }] }),
          fin.lifecycle(["draft", "submitted", "approved", "rejected", "ordered", "cancelled"], "approved"),
          fin.lifecycle(["draft", "submitted", "approved", "rejected", "ordered", "cancelled"], "rejected"),
          fin.lifecycle(["received", "matched", "exception", "approved", "scheduled", "paid", "rejected"], "paid")))),
      h("div", { class: "grid-2" },
        ui.section("Gauges", { icon: "shield" }, h("div", { class: "row" }, fin.gauge(8.8, { label: "Risk score", caption: "low risk", digits: 1 }),
          fin.gauge(52, { label: "Risk score", caption: "medium risk" }), fin.gauge(91, { label: "Risk score", caption: "high risk" }), fin.gauge(null, { label: "Risk score" }))),
        ui.section("Controls and renewals", { icon: "shield" }, h("div", { class: "stack" },
          fin.controlList([{ key: "duplicates", rule: "PROC-03", label: "Possible duplicate invoices", about: "The same supplier and number", severity: "down", count: 3, amount: 18420, rows: [] },
            { key: "splits", rule: "PROC-11", label: "Possible split requests", about: "Requests by one person", severity: "ok", count: 0, amount: 0, rows: [] }], { onClick: say }),
          fin.renewalList([{ title: "Freight framework", reference: "CTR-2025-0113", supplier_name: "Calder Freight Ltd", renewal: "notice_due", days_left: 41, decide_by: "2026-10-06", annual_value: 240000 },
            { title: "Cloud hosting", reference: "CTR-2024-0007", supplier_name: "Northbank Cloud", renewal: "expired", days_left: -12, decide_by: "2026-08-14", annual_value: 96000 }])))),
      ui.section("Controls", { icon: "settings" }, h("div", { class: "stack" },
        fin.periodPicker({ presets: [{ key: "fy_to_date", label: "Year to date (FY2027)", from: "2026-04-01", to: "2026-09-25" }, { key: "last_month", label: "Last month (Aug 2026)", from: "2026-08-01", to: "2026-08-31" }],
          value: { period: "fy_to_date", compare: "prior_year" }, onchange: say }),
        fin.filterBar({ dimensions: { cost_center_id: { label: "Cost centre", options: [{ value: 1, label: "CC-1000 Finance" }, { value: 2, label: "CC-2100 Software Engineering" }] },
          family: { label: "Category family", options: [{ value: "IT", label: "IT" }, { value: "Facilities", label: "Facilities" }] } }, onchange: say }))),
      ui.section("Empty states", { icon: "inbox" }, h("div", { class: "grid-3" }, fin.trend([]), fin.budgetBars([]), fin.pareto([]), fin.treemap(null), fin.aging([]), fin.funnel([]),
        fin.pivot(null), fin.cycleTimes([]), fin.kpis([]), fin.controlList([]), fin.renewalList([]), fin.donut([]), fin.waterfall(null), fin.scorecard(null))),
      ui.section("What was clicked", { icon: "info" }, chosen),
    );
  },
};
